### ISSUE TITLE
ortographical error

### ISSUE THREAD

**Issue by martosv** [CHEMIO/chemistry_rails#5]
I am using your gem, but there is an ortographical error in the vanadium name, because the creators have written venadium instead.

I hope it will be corrected as soon as possible because I need it on my web application.

Thanks!!

**Comment by alexined** [comment]
The typo is fixed. Thanks for catching that. Cheers!

**Comment by alexined** [comment]
@martosv ,

My name is Alexi Ned. I wanted to thank you for you feedback for the typo that you discovered in the gem that we made. I hope it’s working out for you. 

You strike me as interesting person since we have a few things in common. I see that you have a passion for chemistry and that you are getting your feet wet with some coding. 

We are working on a project called CHEM IO, which is a place where researcher can find chemicals for their work. You can checkout our website here http://chem.io. 

My professional email is alexi@chem.io. If you have any question shoot me an email.

Cheers,
